/**
 * Inventory Seeder
 * Tạo dữ liệu kho nguyên liệu
 */

import { db } from '../../config/firebase.config';

export async function seedInventory() {
  const inventory = [
    // Thịt và hải sản
    {
      item_name: 'Thịt bò Úc',
      description: 'Thịt bò Úc cao cấp, tươi ngon',
      category: 'Thịt',
      current_quantity: 50,
      unit: 'kg',
      minimum_quantity: 10,
      reorder_quantity: 30,
      unit_cost: 350000,
      supplier: 'Công ty TNHH Thực phẩm Sạch',
    },
    {
      item_name: 'Thịt heo',
      description: 'Thịt heo sạch, không chất tăng trọng',
      category: 'Thịt',
      current_quantity: 80,
      unit: 'kg',
      minimum_quantity: 20,
      reorder_quantity: 50,
      unit_cost: 120000,
      supplier: 'Công ty TNHH Thực phẩm Sạch',
    },
    {
      item_name: 'Tôm sú',
      description: 'Tôm sú tươi, size lớn',
      category: 'Hải sản',
      current_quantity: 30,
      unit: 'kg',
      minimum_quantity: 5,
      reorder_quantity: 20,
      unit_cost: 450000,
      supplier: 'Công ty Hải sản Biển Đông',
    },
    {
      item_name: 'Mực ống',
      description: 'Mực ống tươi, đông lạnh',
      category: 'Hải sản',
      current_quantity: 25,
      unit: 'kg',
      minimum_quantity: 5,
      reorder_quantity: 15,
      unit_cost: 280000,
      supplier: 'Công ty Hải sản Biển Đông',
    },
    {
      item_name: 'Cá hồi',
      description: 'Cá hồi Na Uy nhập khẩu',
      category: 'Hải sản',
      current_quantity: 20,
      unit: 'kg',
      minimum_quantity: 5,
      reorder_quantity: 15,
      unit_cost: 550000,
      supplier: 'Công ty Hải sản Biển Đông',
    },

    // Rau củ
    {
      item_name: 'Rau xà lách',
      description: 'Rau xà lách tươi, hữu cơ',
      category: 'Rau củ',
      current_quantity: 15,
      unit: 'kg',
      minimum_quantity: 3,
      reorder_quantity: 10,
      unit_cost: 35000,
      supplier: 'Nông trại Đà Lạt',
    },
    {
      item_name: 'Cà chua',
      description: 'Cà chua Đà Lạt',
      category: 'Rau củ',
      current_quantity: 25,
      unit: 'kg',
      minimum_quantity: 5,
      reorder_quantity: 15,
      unit_cost: 25000,
      supplier: 'Nông trại Đà Lạt',
    },
    {
      item_name: 'Hành tây',
      description: 'Hành tây tím',
      category: 'Rau củ',
      current_quantity: 20,
      unit: 'kg',
      minimum_quantity: 5,
      reorder_quantity: 15,
      unit_cost: 18000,
      supplier: 'Nông trại Đà Lạt',
    },
    {
      item_name: 'Khoai tây',
      description: 'Khoai tây Đà Lạt',
      category: 'Rau củ',
      current_quantity: 40,
      unit: 'kg',
      minimum_quantity: 10,
      reorder_quantity: 25,
      unit_cost: 22000,
      supplier: 'Nông trại Đà Lạt',
    },

    // Gia vị
    {
      item_name: 'Muối',
      description: 'Muối biển tinh khiết',
      category: 'Gia vị',
      current_quantity: 50,
      unit: 'kg',
      minimum_quantity: 10,
      reorder_quantity: 30,
      unit_cost: 8000,
      supplier: 'Công ty Gia vị Việt Nam',
    },
    {
      item_name: 'Đường',
      description: 'Đường trắng tinh luyện',
      category: 'Gia vị',
      current_quantity: 60,
      unit: 'kg',
      minimum_quantity: 15,
      reorder_quantity: 40,
      unit_cost: 18000,
      supplier: 'Công ty Gia vị Việt Nam',
    },
    {
      item_name: 'Nước mắm',
      description: 'Nước mắm Phú Quốc 40 độ đạm',
      category: 'Gia vị',
      current_quantity: 30,
      unit: 'l',
      minimum_quantity: 10,
      reorder_quantity: 20,
      unit_cost: 85000,
      supplier: 'Công ty Gia vị Việt Nam',
    },
    {
      item_name: 'Dầu ăn',
      description: 'Dầu đậu nành cao cấp',
      category: 'Gia vị',
      current_quantity: 40,
      unit: 'l',
      minimum_quantity: 10,
      reorder_quantity: 25,
      unit_cost: 45000,
      supplier: 'Công ty Gia vị Việt Nam',
    },

    // Ngũ cốc
    {
      item_name: 'Gạo tẻ',
      description: 'Gạo ST25 cao cấp',
      category: 'Ngũ cốc',
      current_quantity: 200,
      unit: 'kg',
      minimum_quantity: 50,
      reorder_quantity: 150,
      unit_cost: 28000,
      supplier: 'Công ty Lương thực Miền Nam',
    },
    {
      item_name: 'Bún tươi',
      description: 'Bún tươi làm hàng ngày',
      category: 'Ngũ cốc',
      current_quantity: 50,
      unit: 'kg',
      minimum_quantity: 10,
      reorder_quantity: 30,
      unit_cost: 18000,
      supplier: 'Xưởng bánh Hà Nội',
    },
    {
      item_name: 'Bánh phở',
      description: 'Bánh phở tươi',
      category: 'Ngũ cốc',
      current_quantity: 60,
      unit: 'kg',
      minimum_quantity: 15,
      reorder_quantity: 40,
      unit_cost: 20000,
      supplier: 'Xưởng bánh Hà Nội',
    },
    {
      item_name: 'Mì trứng',
      description: 'Mì trứng tươi',
      category: 'Ngũ cốc',
      current_quantity: 40,
      unit: 'kg',
      minimum_quantity: 10,
      reorder_quantity: 25,
      unit_cost: 35000,
      supplier: 'Xưởng bánh Hà Nội',
    },

    // Đồ uống
    {
      item_name: 'Cà phê hạt',
      description: 'Cà phê Arabica nguyên chất',
      category: 'Đồ uống',
      current_quantity: 20,
      unit: 'kg',
      minimum_quantity: 5,
      reorder_quantity: 15,
      unit_cost: 280000,
      supplier: 'Công ty Cà phê Trung Nguyên',
    },
    {
      item_name: 'Trà xanh',
      description: 'Trà xanh Thái Nguyên',
      category: 'Đồ uống',
      current_quantity: 10,
      unit: 'kg',
      minimum_quantity: 2,
      reorder_quantity: 8,
      unit_cost: 350000,
      supplier: 'Công ty Trà Việt',
    },
    {
      item_name: 'Sữa tươi',
      description: 'Sữa tươi không đường',
      category: 'Đồ uống',
      current_quantity: 50,
      unit: 'l',
      minimum_quantity: 10,
      reorder_quantity: 30,
      unit_cost: 32000,
      supplier: 'Công ty Sữa Vinamilk',
    },
  ];

  const createdInventory = [];
  for (const item of inventory) {
    const docRef = await db.collection('inventory').add({
      ...item,
      last_restocked_at: new Date(),
      created_at: new Date(),
      updated_at: new Date(),
    });
    createdInventory.push({ id: docRef.id, ...item });
  }

  return createdInventory;
}
